spring:
  cloud:
    config:
      server:
        git:
          uri: 
          username:
          password: 
          skipSslValidation: true
  application:
    name: config-server
server:
  port: 8888
